version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 92code-doc-generator
    container_name: 92code-doc-generator-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./data:/var/www/storage
    ports:
      - "8000:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: 92code-doc-generator-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 92code
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
